# Define a helper to resolve Node modules
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Load React Native and react-native-permissions setup
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')


platform :ios, min_ios_version_supported
prepare_react_native_project!
use_frameworks! :linkage => :static

# Fix FirebaseCoreInternal + GoogleUtilities issue
pod 'FirebaseCore', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true


pod 'Firebase/Messaging'


# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

target 'TexaApp_34' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  setup_permissions([
    'Camera', # 👈 we enable Camera permission here
    # add more if needed, e.g. 'PhotoLibrary', 'Microphone'
  ])
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNFileViewer', :path => '../node_modules/react-native-file-viewer'

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Remove accessibility duplicate issue (sometimes happens with new RN)
    installer.pods_project.targets.each do |target|
      if target.name == "React-Core-AccessibilityResources"
        target.remove_from_project
      end
    end
  end
end
